import { defineConfig } from "tsup"

export default defineConfig({
  entry: {
    index: "src/index.ts",
    utils: "src/lib/utils.ts",
    ...Object.fromEntries(
      [
        "accordion",
        "alert-dialog",
        "alert",
        "aspect-ratio",
        "avatar",
        "badge",
        "breadcrumb",
        "button",
        "calendar",
        "card",
        "carousel",
        "chart",
        "checkbox",
        "collapsible",
        "command",
        "context-menu",
        "dialog",
        "drawer",
        "dropdown-menu",
        "form",
        "hover-card",
        "input-otp",
        "input",
        "label",
        "menubar",
        "navigation-menu",
        "pagination",
        "popover",
        "progress",
        "radio-group",
        "resizable",
        "scroll-area",
        "select",
        "separator",
        "sheet",
        "sidebar",
        "skeleton",
        "slider",
        "sonner",
        "switch",
        "table",
        "tabs",
        "textarea",
        "toast",
        "toaster",
        "toggle-group",
        "toggle",
        "tooltip",
      ].map((name) => [`components/ui/${name}`, `src/components/ui/${name}.tsx`])
    ),
  },
  format: ["esm"],
  dts: {
    resolve: true,
  },
  clean: true,
  external: [
    "react",
    "react-dom",
    "@radix-ui/*",
    "cmdk",
    "date-fns",
    "embla-carousel-react",
    "next-themes",
    "react-day-picker",
    "sonner",
    "vaul",
    "zod",
  ],
  treeshake: true,
  sourcemap: true,
  minify: true,
  outDir: "dist",
  esbuildOptions(options) {
    options.banner = {
      js: '"use client";',
    }
  },
  onSuccess: "echo '🎉 Build complete!'",
}) 